"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const here = path.join(__dirname, "..");
const config = require("../electron-builder.config.cjs");

/// Packaging rules that are invisible when broken.
///
/// A wrong artifact name does not fail a build, fail a test, or fail a release. It produces a
/// published installer whose name no longer matches the updater feed pointing at it, and the only
/// symptom is a 404 for whoever tries to update - months later, and only for the people who already
/// installed it.

const TARGETS = ["win", "mac"];

test("every platform sets its own artifact name, with no spaces", () => {
  // GitHub rewrites spaces to dots on upload, so "Trypthos Setup 0.4.3.exe" is published as
  // "Trypthos.Setup.0.4.3.exe" while latest.yml still names it with hyphens. electron-builder's own
  // publisher normalised that; publishing from a separate job does not.
  for (const target of TARGETS) {
    const name = config[target].artifactName;
    assert.ok(name, `${target} must set artifactName rather than leave it to the default`);
    assert.ok(!name.includes(" "), `${target} artifactName must not contain a space`);
  }
});

test("the macOS artifact name is qualified by architecture", () => {
  // Without it, an arm64 and an x64 build produce the same filename and collide in one release.
  assert.match(config.mac.artifactName, /\$\{arch\}/);
});

test("no global artifactName overrides the per-target ones", () => {
  // A global name applies to every target, which is how the .dmg lost its architecture suffix.
  assert.equal(config.artifactName, undefined);
});

test("the updater feed has somewhere to be written to", () => {
  // The publish block is what makes electron-builder emit latest.yml and latest-mac.yml. It does not
  // publish - the workflow does that from one job - but removing it silently drops the feed.
  assert.ok(Array.isArray(config.publish) && config.publish.length > 0);
  assert.equal(config.publish[0].provider, "github");
});

test("the renderer is packaged with the app", () => {
  const resources = config.extraResources ?? [];
  assert.ok(
    resources.some((entry) => entry.to === "app"),
    "the built renderer must be copied into resources/app, or the window opens blank",
  );
});

test("macOS builds are explicitly unsigned rather than accidentally so", () => {
  // Stated in the config and in the README. If signing is ever set up, this test is the reminder
  // that the README claim needs changing too.
  assert.equal(config.mac.identity, null);
});

// The resource filter must name the tray files, not a whole extension: "*.png" also swept build/
// icon.png into resources, and "*.ico" would sweep the 9 KB app icon in with the tray's.
test("only the tray icons are packed as resources, by name", () => {
  const entry = (config.extraResources ?? []).find((item) => item.to === "build");
  assert.ok(entry, "the tray resource entry must exist");
  assert.ok(Array.isArray(entry.filter) && entry.filter.length > 0, "the entry must filter");
  for (const pattern of entry.filter) {
    assert.match(pattern, /^tray/, `resource filter "${pattern}" must be tray-only`);
  }
});

test("each platform reads the tray icon in the format its shell wants", () => {
  const { trayIconFileFor } = require("../src/tray");
  // An .ico so Windows picks the size for the DPI itself; a Template PNG pair so macOS can recolour
  // it; a plain PNG everywhere else.
  assert.equal(trayIconFileFor("win32"), "tray.ico");
  assert.equal(trayIconFileFor("darwin"), "trayTemplate.png");
  assert.equal(trayIconFileFor("linux"), "tray.png");
});

test("the tray icons are packed outside the asar", () => {
  // Electron's Tray reads its icon from disk and cannot open an archive, so an icon packed inside
  // app.asar produces a tray with no icon - which looks like the feature not working at all.
  const resources = config.extraResources ?? [];
  assert.ok(
    resources.some((entry) => entry.to === "build"),
    "tray icons must be packed as extraResources, not into the asar",
  );
});

// electron-builder falls back to its own default icon for any target left unset, and that failure
// has no other symptom: the app builds, packages and runs normally with a generic icon in the
// taskbar, Dock and installer, and nobody notices until someone actually looks.
test("every platform points electron-builder at the generated app icon", () => {
  assert.equal(config.win.icon, "build/icon.ico");
  assert.equal(config.mac.icon, "build/icon.icns");
  assert.equal(config.linux.icon, "build/icon.png");
});

// The README explains why these three, and not one shared icon: electron-builder consumes
// build/icon.* at BUILD time, not at runtime, so - unlike the tray PNGs above - it does not need to
// be packed as an extraResource. It is generated by `npm run icons` (predist), same as the tray
// icons, and is gitignored rather than committed.
test("the app icon is not packed as a runtime resource, unlike the tray icons", () => {
  const resources = config.extraResources ?? [];
  assert.ok(
    !resources.some((entry) => String(entry.from ?? entry).includes("icon.")),
    "build/icon.* is consumed by electron-builder at build time and must not also ship as a resource",
  );
});

test("the App User Model ID matches the packaged appId", () => {
  // Windows drops every toast when these disagree - silently, with no error and nothing shown. The
  // installer sets the Start Menu shortcut's identity from appId, so main must announce the same one.
  const main = fs.readFileSync(path.join(here, "src", "main.js"), "utf8");
  const declared = /APP_USER_MODEL_ID = "([^"]+)"/.exec(main)?.[1];

  assert.ok(declared, "main.js must set an App User Model ID");
  assert.equal(declared, config.appId, "the identity must match the appId the installer uses");
});
